name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
- uses: actions/checkout@v4

- name: Setup .NET
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: 8.0 # Ou a versão que você usa

- name: Restore .NET
  run: dotnet restore MinhasFinancasTests.sln

- name: Build and Test .NET
  run: dotnet test MinhasFinancasTests.sln --no-restore

- name: Install Node.js
  uses: actions/setup-node@v4
  with:
    node-version: 20

- name: Install Dependencies and Playwright
  run: |
    npm install
    npx playwright install --with-deps

- name: Run Playwright Tests
  run: npx playwright test
      
